name: nasa-pushback
channels:
  - conda-forge
  - defaults
dependencies:
  - catboost=1.1.1
  - cudatoolkit=11.2
  - eigen=3.4.0
  - keras=2.11.0
  - lightgbm=3.3.5
  - loguru=0.6.0
  - mkl=2022.2.1
  - networkx=3.0
  - numba=0.56.4
  - numpy=1.23.5
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.0
  - pytest=7.2.1
  - python=3.10.9
  - pytorch=1.13.1
  - pytorch-gpu=1.13.1=cuda112py310*
  - pytorch-lightning=1.9.1
  - scikit-image=0.19.3
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - setuptools=67.1.0
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.9
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-gpu=2.11.0=cuda112py310*
  - tensorflow-estimator=2.11.0
  - torchmetrics=0.11.1
  - tqdm=4.64.1
  - xgboost=1.7.1=cuda112py310*
