name: condaenv
channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - eigen=3.4.0
  - keras=2.11.0
  - loguru=0.6.0
  - mkl=2022.2.1
  - networkx=3.0
  - numba=0.56.4
  - numpy=1.23.5
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.0
  - pytest=7.2.1
  - python=3.10.9
  - pytorch=1.13.1
  - pytorch-cpu=1.13.1
  - pytorch-lightning=1.9.1
  - pyvips=2.2.1
  - scikit-image=0.19.3
  - scikit-learn=1.2.2
  - scipy=1.10.0
  - setuptools=67.1.0
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.9
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-cpu=2.11.0
  - tensorflow-estimator=2.11.0
  - torchmetrics=0.11.1
  - torchvision=0.14.1
  - transformers=4.27.4
  - tqdm=4.64.1
  - segmentation-models-pytorch==0.2.1
  - xgboost==1.7.4
  - openslide-python==1.2.0
  - timm==0.4.12
  - opencv-python-headless==4.7.0.72
  - einops==0.6.1
  - rtree==1.0.1
  - shapely==2.0.1
  - catboost==1.2
  - lightgbm==3.3.5 
  - pip:
    - staintools==2.1.2
    - spams==2.6.5.4